# Site settings
title: moehrenzahn.de
email: moehrenzahn@icloud.com
description: Weblog von Max Melzer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://moehrenzahn.de" # the base hostname & protocol for your site
permalink: :title/
twitter_username: _maxmelzer

# Build settings
markdown: kramdown

kramdown:
   smart_quotes: lsquo,rsquo,ldquo,rdquo
