# Site settings
title: moehrenzahn.de
email: moehrenzahn@icloud.com
description: Weblog von Max Melzer
subtitle: Weblog von <a href="/ueber">Max Melzer</a><span class="dot">•</span>über <a href="/categories/theologie/">Theologie</a> und <a href="/categories/technologie/">Technologie</a> 
subtitle_en: Weblog of <a href="/en/about/">Max Melzer</a><span class="dot">•</span>on tech and theology
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://moehrenzahn.de" # the base hostname & protocol for your site
permalink: :title/
twitter_username: _maxmelzer

# Build settings
markdown: kramdown

kramdown:
   smart_quotes: lsquo,rsquo,ldquo,rdquo
