# Site settings
title: moehrenzahn.de
email: hi@moehrenzahn.de
description: Weblog von Max Melzer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.moehrenzahn.de" # the base hostname & protocol for your site
permalink: :title/
twitter_username: _maxmelzer

# Build settings
markdown: kramdown
exclude: [_drafts/Abgelehnt/, makefile]

kramdown:
   smart_quotes: lsquo,rsquo,ldquo,rdquo
