# Site settings
title: moehrenzahn.de
email: hi@moehrenzahn.de
description: Weblog von Max Melzer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.moehrenzahn.de" # the base hostname & protocol for your site
permalink: :title/

collections:
   projects:
      layout: project
      sort_by: date
      output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: projects
    values:
      layout: project
      layout-width: 900px
  -
    scope:
      path: "paintings"
    values:
      layout: painting
      permalink: /paintings/:year-:month-:day-:title/
      lang: en # All painting pages are in english
  -
    scope:
      path: "/en/*"
    values:
      lang: en

# Build settings
markdown: kramdown
exclude: [_drafts/Abgelehnt/, makefile, .idea/]

kramdown:
   smart_quotes: lsquo,rsquo,ldquo,rdquo
